# -*- coding: utf-8 -*-
"""requirements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QBNx5QyhbovfyE3vljpaz82YQbvFQsYI
"""

!pip install  beautifulsoup4
!pip install pandas
!pip install PyMuPDF
!pip install tqdm

