# -*- coding: utf-8 -*-
"""scraper.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N2ivjL19HhO9k45wxpd0-cO7h_78gwtP
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import fitz  # PyMuPDF
from io import BytesIO
from tqdm import tqdm

# URL base da consulta de produção legislativa do vereador Fabrício
URL_BASE = "https://guaratingueta.camarasempapel.com.br"
URL_CONSULTA = f"{URL_BASE}/consulta-producao.aspx?autor=214"

# Função para extrair os links dos processos legislativos
def extrair_links_processo():
    r = requests.get

# Salva a tabela no repositório como CSV
df_final.to_csv("tabela_legislativa.csv", index=False)
