name: Atualizar Tabela Legislativa

on:
  schedule:
    - cron: '0 9 * * *'  # Roda todos os dias às 9h UTC (6h no Brasil)
  workflow_dispatch:  # Permite execução manual

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install -r scraper-fabricio/requirements.txt

      - name: Executar scraper
        run: python scraper-fabricio/scraper.py

      - name: Verificar alterações
        run: git diff

      - name: Commit e push se houver mudanças
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'

          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "Atualização automática da tabela legislativa"
            git push
          else
            echo "Nenhuma alteração detectada, nada para commitar."
          fi
